on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.server_url == 'https://github.com' }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: rp
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.rp.outputs.release_created && env.NODE_AUTH_TOKEN != '' }}
      - uses: actions/setup-node@v4
        if: ${{ steps.rp.outputs.release_created && env.NODE_AUTH_TOKEN != '' }}
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        if: ${{ steps.rp.outputs.release_created && env.NODE_AUTH_TOKEN != '' }}
      - run: npm publish
        if: ${{ steps.rp.outputs.release_created && env.NODE_AUTH_TOKEN != '' }}
